//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cent;cents;cents.
        /// </summary>
        public static string Cent {
            get {
                return ResourceManager.GetString("Cent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+_1 Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dollar;dollars;dollars.
        /// </summary>
        public static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        public static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighteen.
        /// </summary>
        public static string Eighteen {
            get {
                return ResourceManager.GetString("Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty.
        /// </summary>
        public static string Eighty {
            get {
                return ResourceManager.GetString("Eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eleven.
        /// </summary>
        public static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your numer.
        /// </summary>
        public static string EnterNumber {
            get {
                return ResourceManager.GetString("EnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifteen.
        /// </summary>
        public static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty.
        /// </summary>
        public static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forty.
        /// </summary>
        public static string Forty {
            get {
                return ResourceManager.GetString("Forty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourteen.
        /// </summary>
        public static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hundred;hundred;hundred.
        /// </summary>
        public static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to million;million;million.
        /// </summary>
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine.
        /// </summary>
        public static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nineteen.
        /// </summary>
        public static string Nineteen {
            get {
                return ResourceManager.GetString("Nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety.
        /// </summary>
        public static string Ninety {
            get {
                return ResourceManager.GetString("Ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not number.
        /// </summary>
        public static string NotNumber {
            get {
                return ResourceManager.GetString("NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one;one.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must have 3 forms divided by &quot;;&quot;.
        /// </summary>
        public static string PlurlError {
            get {
                return ResourceManager.GetString("PlurlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &lt;ENTER&gt; to terminate service.
        /// </summary>
        public static string PressEnter {
            get {
                return ResourceManager.GetString("PressEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of number from 0 up to 999999999,99.
        /// </summary>
        public static string RangeOfNumber {
            get {
                return ResourceManager.GetString("RangeOfNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is ready.
        /// </summary>
        public static string ServiceReady {
            get {
                return ResourceManager.GetString("ServiceReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seven.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventeen.
        /// </summary>
        public static string Seventeen {
            get {
                return ResourceManager.GetString("Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy.
        /// </summary>
        public static string Seventy {
            get {
                return ResourceManager.GetString("Seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixteen.
        /// </summary>
        public static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty.
        /// </summary>
        public static string Sixty {
            get {
                return ResourceManager.GetString("Sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ten.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirteen.
        /// </summary>
        public static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty.
        /// </summary>
        public static string Thirty {
            get {
                return ResourceManager.GetString("Thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thousand;thousand;thousand.
        /// </summary>
        public static string Thousand {
            get {
                return ResourceManager.GetString("Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout waiting. No answer from server.
        /// </summary>
        public static string TimeoutWaiting {
            get {
                return ResourceManager.GetString("TimeoutWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twelve.
        /// </summary>
        public static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty.
        /// </summary>
        public static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two;two.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the remote server.
        /// </summary>
        public static string UnableConnect {
            get {
                return ResourceManager.GetString("UnableConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zero.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
